services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    user: "mysql"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure